name: Lab Inspiration
favicon: null
layout_spectrum: 0.4418388574849814
typography_spectrum: 0.6388989207334816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#41372e'
    - '#675d54'
    - '#a6a5a1'
  brandStrength: 0.4779005197342485
  lightness: 0.6623721641954035
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
