name: Lab Inspiration
favicon: null
layout_spectrum: 0.4418388574849814
typography_spectrum: 0.6388989207334816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2cb3c7'
    - '#c2d5db'
    - '#0a1a33'
    - '#c37e5d'
    - '#567383'
  brandStrength: 0.625
  lightness: 0.6623721641954035
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
